spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingdb
    username: admin
    password: Admin@1234
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8084